server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./testdb;DB_CLOSE_ON_EXIT=FALSE
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

services.url:
  image-service: http://localhost:8086/
  some-other-service: http://localhost:8087/
---
spring:
  profiles: ci

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://taas-postgres:5432/taas_teams_service
    username: # env param
    password: # env param
